/*
 * SPDX-FileCopyrightText: Copyright (c) 2016-2025 Objectionary.com
 * SPDX-License-Identifier: MIT
 */
package org.eolang.sodg;

import com.jcabi.manifests.Manifests;
import java.time.Instant;
import java.time.ZoneOffset;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;

/**
 * A piece of text generated in runtime, to be injected into the files
 * that we generate as output, for `.sodg` files.
 * @since 0.27
 */
final class Disclaimer {

    /**
     * Sodg version.
     */
    private final String version;

    /**
     * Ctor.
     * @param vrsn Version
     */
    Disclaimer(final String vrsn) {
        this.version = vrsn;
    }

    @Override
    public String toString() {
        return String.join(
            "",
            "This file was auto-generated by sodg-maven-plugin (",
            this.version,
            " ",
            "EO ",
            Manifests.read("EO-Version"),
            " ",
            Manifests.read("EO-Revision"),
            " ",
            Manifests.read("EO-Dob"),
            ") on ",
            ZonedDateTime.ofInstant(
                Disclaimer.resolved(System.getenv("SOURCE_DATE_EPOCH")), ZoneOffset.UTC
            ).format(DateTimeFormatter.ISO_INSTANT),
            "; your changes will be discarded on the next build"
        );
    }

    /**
     * Resolve the timestamp to embed, honouring {@code SOURCE_DATE_EPOCH} for
     * reproducible builds (https://reproducible-builds.org/specs/source-date-epoch/)
     * and falling back to the current time when it isn't set.
     * @param epoch Value of the {@code SOURCE_DATE_EPOCH} environment variable, or
     *  {@code null} if it isn't set
     * @return The timestamp
     */
    static Instant resolved(final String epoch) {
        final Instant now;
        if (epoch == null) {
            now = Instant.now();
        } else {
            now = Instant.ofEpochSecond(Long.parseLong(epoch));
        }
        return now;
    }
}
