/*
 * SPDX-FileCopyrightText: Copyright (c) 2016-2025 Objectionary.com
 * SPDX-License-Identifier: MIT
 */
package org.eolang.sodg;

import com.jcabi.manifests.Manifests;
import java.time.ZoneOffset;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;

/**
 * A piece of text generated in runtime, to be injected into the files
 * that we generate as output, for `.sodg` files.
 * @since 0.27
 */
final class Disclaimer {

    /**
     * Sodg version.
     */
    private final String version;

    /**
     * Ctor.
     * @param vrsn Version
     */
    Disclaimer(final String vrsn) {
        this.version = vrsn;
    }

    @Override
    public String toString() {
        return String.join(
            "",
            "This file was auto-generated by sodg-maven-plugin (",
            this.version,
            " ",
            "EO ",
            Manifests.read("EO-Version"),
            " ",
            Manifests.read("EO-Revision"),
            " ",
            Manifests.read("EO-Dob"),
            ") on ",
            ZonedDateTime.now(ZoneOffset.UTC).format(
                DateTimeFormatter.ISO_INSTANT
            ),
            "; your changes will be discarded on the next build"
        );
    }
}
